<?php


/**
 * This class defines the structure of the 'maws_filter' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Mar 20 00:50:38 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class MawsFilterTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MawsFilterTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('maws_filter');
		$this->setPhpName('MawsFilter');
		$this->setClassname('MawsFilter');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', false, 255, '');
		$this->addColumn('RESOURCE', 'Resource', 'VARCHAR', false, 255, null);
		$this->addColumn('RESOURCE_TYPE', 'ResourceType', 'INTEGER', true, null, 0);
		$this->addColumn('RESOURCE_METHOD', 'ResourceMethod', 'INTEGER', true, null, 0);
		$this->addColumn('RESOURCE_LOGIN', 'ResourceLogin', 'VARCHAR', false, 255, null);
		$this->addColumn('RESOURCE_PASS', 'ResourcePass', 'VARCHAR', false, 255, null);
		$this->addColumn('RESOURCE_PARAMS', 'ResourceParams', 'LONGVARCHAR', false, null, '');
		$this->addColumn('FILTER', 'Filter', 'LONGVARCHAR', false, null, '');
		$this->addColumn('FILTER_TYPE', 'FilterType', 'INTEGER', true, null, 0);
		$this->addColumn('ACTION', 'Action', 'VARCHAR', false, 255, '');
		$this->addColumn('ACTION_TYPE', 'ActionType', 'INTEGER', true, null, 0);
		$this->addColumn('ACTION_PARAM1', 'ActionParam1', 'VARCHAR', false, 255, '');
		$this->addColumn('ACTION_PARAM2', 'ActionParam2', 'VARCHAR', false, 255, '');
		$this->addColumn('ACTION_PARAM3', 'ActionParam3', 'VARCHAR', false, 255, '');
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('MawsFilterResult', 'MawsFilterResult', RelationMap::ONE_TO_MANY, array('id' => 'filter_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // MawsFilterTableMap
