<?php


/**
 * This class defines the structure of the 'maws_parser' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat May  8 12:48:26 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class MawsParserTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MawsParserTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('maws_parser');
		$this->setPhpName('MawsParser');
		$this->setClassname('MawsParser');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', false, 255, '');
		$this->addColumn('DESCRIPTION', 'Description', 'VARCHAR', false, 255, '');
		$this->addColumn('ACCESS', 'Access', 'INTEGER', true, null, 0);
		$this->addColumn('RESOURCE_URL', 'ResourceUrl', 'VARCHAR', false, 255, null);
		$this->addColumn('RESOURCE_TYPE', 'ResourceType', 'INTEGER', true, null, 0);
		$this->addColumn('RESOURCE_PARAMS', 'ResourceParams', 'LONGVARCHAR', false, null, '');
		$this->addColumn('RESOURCE_METHOD', 'ResourceMethod', 'INTEGER', true, null, 0);
		$this->addColumn('RESOURCE_LOGIN', 'ResourceLogin', 'VARCHAR', false, 255, null);
		$this->addColumn('RESOURCE_PASS', 'ResourcePass', 'VARCHAR', false, 255, null);
		$this->addColumn('FILTER_TYPE', 'FilterType', 'INTEGER', true, null, 0);
		$this->addColumn('FILTER_PARAMS', 'FilterParams', 'LONGVARCHAR', false, null, '');
		$this->addColumn('ACTION_TYPE', 'ActionType', 'INTEGER', true, null, 0);
		$this->addColumn('ACTION_PARAMS', 'ActionParams', 'LONGVARCHAR', false, null, '');
		$this->addColumn('RESULT_TYPE', 'ResultType', 'INTEGER', true, null, 0);
		$this->addForeignKey('OWNER_ID', 'OwnerId', 'INTEGER', 'sf_guard_user', 'ID', true, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfGuardUser', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('owner_id' => 'id', ), null, null);
    $this->addRelation('MawsParserResult', 'MawsParserResult', RelationMap::ONE_TO_MANY, array('id' => 'parser_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // MawsParserTableMap
