<?php


/**
 * This class defines the structure of the 'maws_filter_result' table.
 *
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Tue Mar 23 22:13:06 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class MawsFilterResultTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MawsFilterResultTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('maws_filter_result');
		$this->setPhpName('MawsFilterResult');
		$this->setClassname('MawsFilterResult');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', false, 255, '');
		$this->addForeignKey('FILTER_ID', 'FilterId', 'INTEGER', 'maws_filter', 'ID', true, null, null);
		$this->addForeignKey('THREAD_ID', 'ThreadId', 'INTEGER', 'maws_thread', 'ID', true, null, null);
		$this->addColumn('RESULT', 'Result', 'LONGVARCHAR', false, null, '');
		$this->addColumn('IS_DIFF', 'IsDiff', 'INTEGER', false, null, 0);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('MawsFilter', 'MawsFilter', RelationMap::MANY_TO_ONE, array('filter_id' => 'id', ), null, null);
    $this->addRelation('MawsThread', 'MawsThread', RelationMap::MANY_TO_ONE, array('thread_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // MawsFilterResultTableMap
