<?php

/**
 * Base class that represents a row from the 'maws_filter' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Mar 20 00:50:38 2010
 *
 * @package    lib.model.om
 */
abstract class BaseMawsFilter extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        MawsFilterPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the resource field.
	 * @var        string
	 */
	protected $resource;

	/**
	 * The value for the resource_type field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $resource_type;

	/**
	 * The value for the resource_method field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $resource_method;

	/**
	 * The value for the resource_login field.
	 * @var        string
	 */
	protected $resource_login;

	/**
	 * The value for the resource_pass field.
	 * @var        string
	 */
	protected $resource_pass;

	/**
	 * The value for the resource_params field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $resource_params;

	/**
	 * The value for the filter field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $filter;

	/**
	 * The value for the filter_type field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $filter_type;

	/**
	 * The value for the action field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $action;

	/**
	 * The value for the action_type field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $action_type;

	/**
	 * The value for the action_param1 field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $action_param1;

	/**
	 * The value for the action_param2 field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $action_param2;

	/**
	 * The value for the action_param3 field.
	 * Note: this column has a database default value of: ''
	 * @var        string
	 */
	protected $action_param3;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        array MawsFilterResult[] Collection to store aggregation of MawsFilterResult objects.
	 */
	protected $collMawsFilterResults;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMawsFilterResults.
	 */
	private $lastMawsFilterResultCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'MawsFilterPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->name = '';
		$this->resource_type = 0;
		$this->resource_method = 0;
		$this->resource_params = '';
		$this->filter = '';
		$this->filter_type = 0;
		$this->action = '';
		$this->action_type = 0;
		$this->action_param1 = '';
		$this->action_param2 = '';
		$this->action_param3 = '';
	}

	/**
	 * Initializes internal state of BaseMawsFilter object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [resource] column value.
	 * 
	 * @return     string
	 */
	public function getResource()
	{
		return $this->resource;
	}

	/**
	 * Get the [resource_type] column value.
	 * 
	 * @return     int
	 */
	public function getResourceType()
	{
		return $this->resource_type;
	}

	/**
	 * Get the [resource_method] column value.
	 * 
	 * @return     int
	 */
	public function getResourceMethod()
	{
		return $this->resource_method;
	}

	/**
	 * Get the [resource_login] column value.
	 * 
	 * @return     string
	 */
	public function getResourceLogin()
	{
		return $this->resource_login;
	}

	/**
	 * Get the [resource_pass] column value.
	 * 
	 * @return     string
	 */
	public function getResourcePass()
	{
		return $this->resource_pass;
	}

	/**
	 * Get the [resource_params] column value.
	 * 
	 * @return     string
	 */
	public function getResourceParams()
	{
		return $this->resource_params;
	}

	/**
	 * Get the [filter] column value.
	 * 
	 * @return     string
	 */
	public function getFilter()
	{
		return $this->filter;
	}

	/**
	 * Get the [filter_type] column value.
	 * 
	 * @return     int
	 */
	public function getFilterType()
	{
		return $this->filter_type;
	}

	/**
	 * Get the [action] column value.
	 * 
	 * @return     string
	 */
	public function getAction()
	{
		return $this->action;
	}

	/**
	 * Get the [action_type] column value.
	 * 
	 * @return     int
	 */
	public function getActionType()
	{
		return $this->action_type;
	}

	/**
	 * Get the [action_param1] column value.
	 * 
	 * @return     string
	 */
	public function getActionParam1()
	{
		return $this->action_param1;
	}

	/**
	 * Get the [action_param2] column value.
	 * 
	 * @return     string
	 */
	public function getActionParam2()
	{
		return $this->action_param2;
	}

	/**
	 * Get the [action_param3] column value.
	 * 
	 * @return     string
	 */
	public function getActionParam3()
	{
		return $this->action_param3;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = MawsFilterPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v || $this->isNew()) {
			$this->name = $v;
			$this->modifiedColumns[] = MawsFilterPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [resource] column.
	 * 
	 * @param      string $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setResource($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->resource !== $v) {
			$this->resource = $v;
			$this->modifiedColumns[] = MawsFilterPeer::RESOURCE;
		}

		return $this;
	} // setResource()

	/**
	 * Set the value of [resource_type] column.
	 * 
	 * @param      int $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setResourceType($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->resource_type !== $v || $this->isNew()) {
			$this->resource_type = $v;
			$this->modifiedColumns[] = MawsFilterPeer::RESOURCE_TYPE;
		}

		return $this;
	} // setResourceType()

	/**
	 * Set the value of [resource_method] column.
	 * 
	 * @param      int $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setResourceMethod($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->resource_method !== $v || $this->isNew()) {
			$this->resource_method = $v;
			$this->modifiedColumns[] = MawsFilterPeer::RESOURCE_METHOD;
		}

		return $this;
	} // setResourceMethod()

	/**
	 * Set the value of [resource_login] column.
	 * 
	 * @param      string $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setResourceLogin($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->resource_login !== $v) {
			$this->resource_login = $v;
			$this->modifiedColumns[] = MawsFilterPeer::RESOURCE_LOGIN;
		}

		return $this;
	} // setResourceLogin()

	/**
	 * Set the value of [resource_pass] column.
	 * 
	 * @param      string $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setResourcePass($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->resource_pass !== $v) {
			$this->resource_pass = $v;
			$this->modifiedColumns[] = MawsFilterPeer::RESOURCE_PASS;
		}

		return $this;
	} // setResourcePass()

	/**
	 * Set the value of [resource_params] column.
	 * 
	 * @param      string $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setResourceParams($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->resource_params !== $v || $this->isNew()) {
			$this->resource_params = $v;
			$this->modifiedColumns[] = MawsFilterPeer::RESOURCE_PARAMS;
		}

		return $this;
	} // setResourceParams()

	/**
	 * Set the value of [filter] column.
	 * 
	 * @param      string $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setFilter($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->filter !== $v || $this->isNew()) {
			$this->filter = $v;
			$this->modifiedColumns[] = MawsFilterPeer::FILTER;
		}

		return $this;
	} // setFilter()

	/**
	 * Set the value of [filter_type] column.
	 * 
	 * @param      int $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setFilterType($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->filter_type !== $v || $this->isNew()) {
			$this->filter_type = $v;
			$this->modifiedColumns[] = MawsFilterPeer::FILTER_TYPE;
		}

		return $this;
	} // setFilterType()

	/**
	 * Set the value of [action] column.
	 * 
	 * @param      string $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setAction($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->action !== $v || $this->isNew()) {
			$this->action = $v;
			$this->modifiedColumns[] = MawsFilterPeer::ACTION;
		}

		return $this;
	} // setAction()

	/**
	 * Set the value of [action_type] column.
	 * 
	 * @param      int $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setActionType($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->action_type !== $v || $this->isNew()) {
			$this->action_type = $v;
			$this->modifiedColumns[] = MawsFilterPeer::ACTION_TYPE;
		}

		return $this;
	} // setActionType()

	/**
	 * Set the value of [action_param1] column.
	 * 
	 * @param      string $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setActionParam1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->action_param1 !== $v || $this->isNew()) {
			$this->action_param1 = $v;
			$this->modifiedColumns[] = MawsFilterPeer::ACTION_PARAM1;
		}

		return $this;
	} // setActionParam1()

	/**
	 * Set the value of [action_param2] column.
	 * 
	 * @param      string $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setActionParam2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->action_param2 !== $v || $this->isNew()) {
			$this->action_param2 = $v;
			$this->modifiedColumns[] = MawsFilterPeer::ACTION_PARAM2;
		}

		return $this;
	} // setActionParam2()

	/**
	 * Set the value of [action_param3] column.
	 * 
	 * @param      string $v new value
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setActionParam3($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->action_param3 !== $v || $this->isNew()) {
			$this->action_param3 = $v;
			$this->modifiedColumns[] = MawsFilterPeer::ACTION_PARAM3;
		}

		return $this;
	} // setActionParam3()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = MawsFilterPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     MawsFilter The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = MawsFilterPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->name !== '') {
				return false;
			}

			if ($this->resource_type !== 0) {
				return false;
			}

			if ($this->resource_method !== 0) {
				return false;
			}

			if ($this->resource_params !== '') {
				return false;
			}

			if ($this->filter !== '') {
				return false;
			}

			if ($this->filter_type !== 0) {
				return false;
			}

			if ($this->action !== '') {
				return false;
			}

			if ($this->action_type !== 0) {
				return false;
			}

			if ($this->action_param1 !== '') {
				return false;
			}

			if ($this->action_param2 !== '') {
				return false;
			}

			if ($this->action_param3 !== '') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->resource = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->resource_type = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->resource_method = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->resource_login = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resource_pass = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resource_params = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->filter = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->filter_type = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->action = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->action_type = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->action_param1 = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->action_param2 = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->action_param3 = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->created_at = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->updated_at = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 17; // 17 = MawsFilterPeer::NUM_COLUMNS - MawsFilterPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating MawsFilter object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MawsFilterPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = MawsFilterPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collMawsFilterResults = null;
			$this->lastMawsFilterResultCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MawsFilterPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseMawsFilter:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				MawsFilterPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseMawsFilter:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MawsFilterPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseMawsFilter:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(MawsFilterPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(MawsFilterPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseMawsFilter:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				$con->commit();
				MawsFilterPeer::addInstanceToPool($this);
				return $affectedRows;
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = MawsFilterPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = MawsFilterPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += MawsFilterPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collMawsFilterResults !== null) {
				foreach ($this->collMawsFilterResults as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = MawsFilterPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collMawsFilterResults !== null) {
					foreach ($this->collMawsFilterResults as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = MawsFilterPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getResource();
				break;
			case 3:
				return $this->getResourceType();
				break;
			case 4:
				return $this->getResourceMethod();
				break;
			case 5:
				return $this->getResourceLogin();
				break;
			case 6:
				return $this->getResourcePass();
				break;
			case 7:
				return $this->getResourceParams();
				break;
			case 8:
				return $this->getFilter();
				break;
			case 9:
				return $this->getFilterType();
				break;
			case 10:
				return $this->getAction();
				break;
			case 11:
				return $this->getActionType();
				break;
			case 12:
				return $this->getActionParam1();
				break;
			case 13:
				return $this->getActionParam2();
				break;
			case 14:
				return $this->getActionParam3();
				break;
			case 15:
				return $this->getCreatedAt();
				break;
			case 16:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = MawsFilterPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getResource(),
			$keys[3] => $this->getResourceType(),
			$keys[4] => $this->getResourceMethod(),
			$keys[5] => $this->getResourceLogin(),
			$keys[6] => $this->getResourcePass(),
			$keys[7] => $this->getResourceParams(),
			$keys[8] => $this->getFilter(),
			$keys[9] => $this->getFilterType(),
			$keys[10] => $this->getAction(),
			$keys[11] => $this->getActionType(),
			$keys[12] => $this->getActionParam1(),
			$keys[13] => $this->getActionParam2(),
			$keys[14] => $this->getActionParam3(),
			$keys[15] => $this->getCreatedAt(),
			$keys[16] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = MawsFilterPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setResource($value);
				break;
			case 3:
				$this->setResourceType($value);
				break;
			case 4:
				$this->setResourceMethod($value);
				break;
			case 5:
				$this->setResourceLogin($value);
				break;
			case 6:
				$this->setResourcePass($value);
				break;
			case 7:
				$this->setResourceParams($value);
				break;
			case 8:
				$this->setFilter($value);
				break;
			case 9:
				$this->setFilterType($value);
				break;
			case 10:
				$this->setAction($value);
				break;
			case 11:
				$this->setActionType($value);
				break;
			case 12:
				$this->setActionParam1($value);
				break;
			case 13:
				$this->setActionParam2($value);
				break;
			case 14:
				$this->setActionParam3($value);
				break;
			case 15:
				$this->setCreatedAt($value);
				break;
			case 16:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = MawsFilterPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setResource($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setResourceType($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setResourceMethod($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setResourceLogin($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setResourcePass($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setResourceParams($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFilter($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setFilterType($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setAction($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setActionType($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setActionParam1($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setActionParam2($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setActionParam3($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setCreatedAt($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setUpdatedAt($arr[$keys[16]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(MawsFilterPeer::DATABASE_NAME);

		if ($this->isColumnModified(MawsFilterPeer::ID)) $criteria->add(MawsFilterPeer::ID, $this->id);
		if ($this->isColumnModified(MawsFilterPeer::NAME)) $criteria->add(MawsFilterPeer::NAME, $this->name);
		if ($this->isColumnModified(MawsFilterPeer::RESOURCE)) $criteria->add(MawsFilterPeer::RESOURCE, $this->resource);
		if ($this->isColumnModified(MawsFilterPeer::RESOURCE_TYPE)) $criteria->add(MawsFilterPeer::RESOURCE_TYPE, $this->resource_type);
		if ($this->isColumnModified(MawsFilterPeer::RESOURCE_METHOD)) $criteria->add(MawsFilterPeer::RESOURCE_METHOD, $this->resource_method);
		if ($this->isColumnModified(MawsFilterPeer::RESOURCE_LOGIN)) $criteria->add(MawsFilterPeer::RESOURCE_LOGIN, $this->resource_login);
		if ($this->isColumnModified(MawsFilterPeer::RESOURCE_PASS)) $criteria->add(MawsFilterPeer::RESOURCE_PASS, $this->resource_pass);
		if ($this->isColumnModified(MawsFilterPeer::RESOURCE_PARAMS)) $criteria->add(MawsFilterPeer::RESOURCE_PARAMS, $this->resource_params);
		if ($this->isColumnModified(MawsFilterPeer::FILTER)) $criteria->add(MawsFilterPeer::FILTER, $this->filter);
		if ($this->isColumnModified(MawsFilterPeer::FILTER_TYPE)) $criteria->add(MawsFilterPeer::FILTER_TYPE, $this->filter_type);
		if ($this->isColumnModified(MawsFilterPeer::ACTION)) $criteria->add(MawsFilterPeer::ACTION, $this->action);
		if ($this->isColumnModified(MawsFilterPeer::ACTION_TYPE)) $criteria->add(MawsFilterPeer::ACTION_TYPE, $this->action_type);
		if ($this->isColumnModified(MawsFilterPeer::ACTION_PARAM1)) $criteria->add(MawsFilterPeer::ACTION_PARAM1, $this->action_param1);
		if ($this->isColumnModified(MawsFilterPeer::ACTION_PARAM2)) $criteria->add(MawsFilterPeer::ACTION_PARAM2, $this->action_param2);
		if ($this->isColumnModified(MawsFilterPeer::ACTION_PARAM3)) $criteria->add(MawsFilterPeer::ACTION_PARAM3, $this->action_param3);
		if ($this->isColumnModified(MawsFilterPeer::CREATED_AT)) $criteria->add(MawsFilterPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(MawsFilterPeer::UPDATED_AT)) $criteria->add(MawsFilterPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(MawsFilterPeer::DATABASE_NAME);

		$criteria->add(MawsFilterPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of MawsFilter (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setResource($this->resource);

		$copyObj->setResourceType($this->resource_type);

		$copyObj->setResourceMethod($this->resource_method);

		$copyObj->setResourceLogin($this->resource_login);

		$copyObj->setResourcePass($this->resource_pass);

		$copyObj->setResourceParams($this->resource_params);

		$copyObj->setFilter($this->filter);

		$copyObj->setFilterType($this->filter_type);

		$copyObj->setAction($this->action);

		$copyObj->setActionType($this->action_type);

		$copyObj->setActionParam1($this->action_param1);

		$copyObj->setActionParam2($this->action_param2);

		$copyObj->setActionParam3($this->action_param3);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getMawsFilterResults() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMawsFilterResult($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     MawsFilter Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     MawsFilterPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new MawsFilterPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collMawsFilterResults collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMawsFilterResults()
	 */
	public function clearMawsFilterResults()
	{
		$this->collMawsFilterResults = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMawsFilterResults collection (array).
	 *
	 * By default this just sets the collMawsFilterResults collection to an empty array (like clearcollMawsFilterResults());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMawsFilterResults()
	{
		$this->collMawsFilterResults = array();
	}

	/**
	 * Gets an array of MawsFilterResult objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this MawsFilter has previously been saved, it will retrieve
	 * related MawsFilterResults from storage. If this MawsFilter is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array MawsFilterResult[]
	 * @throws     PropelException
	 */
	public function getMawsFilterResults($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MawsFilterPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMawsFilterResults === null) {
			if ($this->isNew()) {
			   $this->collMawsFilterResults = array();
			} else {

				$criteria->add(MawsFilterResultPeer::FILTER_ID, $this->id);

				MawsFilterResultPeer::addSelectColumns($criteria);
				$this->collMawsFilterResults = MawsFilterResultPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MawsFilterResultPeer::FILTER_ID, $this->id);

				MawsFilterResultPeer::addSelectColumns($criteria);
				if (!isset($this->lastMawsFilterResultCriteria) || !$this->lastMawsFilterResultCriteria->equals($criteria)) {
					$this->collMawsFilterResults = MawsFilterResultPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMawsFilterResultCriteria = $criteria;
		return $this->collMawsFilterResults;
	}

	/**
	 * Returns the number of related MawsFilterResult objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related MawsFilterResult objects.
	 * @throws     PropelException
	 */
	public function countMawsFilterResults(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MawsFilterPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMawsFilterResults === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MawsFilterResultPeer::FILTER_ID, $this->id);

				$count = MawsFilterResultPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MawsFilterResultPeer::FILTER_ID, $this->id);

				if (!isset($this->lastMawsFilterResultCriteria) || !$this->lastMawsFilterResultCriteria->equals($criteria)) {
					$count = MawsFilterResultPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collMawsFilterResults);
				}
			} else {
				$count = count($this->collMawsFilterResults);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a MawsFilterResult object to this object
	 * through the MawsFilterResult foreign key attribute.
	 *
	 * @param      MawsFilterResult $l MawsFilterResult
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMawsFilterResult(MawsFilterResult $l)
	{
		if ($this->collMawsFilterResults === null) {
			$this->initMawsFilterResults();
		}
		if (!in_array($l, $this->collMawsFilterResults, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMawsFilterResults, $l);
			$l->setMawsFilter($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MawsFilter is new, it will return
	 * an empty collection; or if this MawsFilter has previously
	 * been saved, it will retrieve related MawsFilterResults from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MawsFilter.
	 */
	public function getMawsFilterResultsJoinMawsThread($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MawsFilterPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMawsFilterResults === null) {
			if ($this->isNew()) {
				$this->collMawsFilterResults = array();
			} else {

				$criteria->add(MawsFilterResultPeer::FILTER_ID, $this->id);

				$this->collMawsFilterResults = MawsFilterResultPeer::doSelectJoinMawsThread($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MawsFilterResultPeer::FILTER_ID, $this->id);

			if (!isset($this->lastMawsFilterResultCriteria) || !$this->lastMawsFilterResultCriteria->equals($criteria)) {
				$this->collMawsFilterResults = MawsFilterResultPeer::doSelectJoinMawsThread($criteria, $con, $join_behavior);
			}
		}
		$this->lastMawsFilterResultCriteria = $criteria;

		return $this->collMawsFilterResults;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collMawsFilterResults) {
				foreach ((array) $this->collMawsFilterResults as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collMawsFilterResults = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseMawsFilter:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseMawsFilter::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseMawsFilter
