<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/05/01 22:27:20
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => true,
  'app_sf_guard_plugin_success_signin_url' => '/main/index',
  'app_sf_guard_plugin_profile_class' => 'sfGuardUserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
  'app_anonymous_login' => 'anonymous',
));
