<?php


/**
 * Skeleton subclass for performing query and update operations on the 'maws_parser' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Mar 24 21:33:38 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MawsParserPeer extends BaseMawsParserPeer {

} // MawsParserPeer
