<?php


/**
 * Skeleton subclass for performing query and update operations on the 'maws_filter' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Mon Mar 15 22:37:03 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MawsFilterPeer extends BaseMawsFilterPeer {

} // MawsFilterPeer
