<?php


/**
 * Skeleton subclass for representing a row from the 'maws_thread' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Mar 20 00:50:38 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MawsThread extends BaseMawsThread {

	/**
	 * Initializes internal state of MawsThread object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}


	public function	__toString()
	{
		return $this->getName().' ['.$this->getId().']';
	}

	/**
	 * Загружает парсер, привязанный к треду, выполняет его, и записывает полученный результат в БД
	 * 
	 */
	public function ProcessParse()
	{
		$MawsParser = MawsParserPeer::retrieveByPk($this->getParserId());
		$arMawsParserResults = $MawsParser->Get();

		$oMawsParserResult = new MawsParserResult();
		$oMawsParserResult->setParserId($this->getParserId());
		$oMawsParserResult->setThreadId($this->getId());

		if ($arMawsParserResults != MawsParser::EMPTY_RESOURCE )
		{
			$oMawsParserResult ->setResult(serialize($arMawsParserResults));
			$oMawsParserResult ->setIsDiff(1);
		}
		else
		{
			$oMawsParserResult ->setResult(MawsParser::EMPTY_RESOURCE);
			$oMawsParserResult ->setIsDiff(1);
		}

		$oMawsParserResult ->setResultType($MawsParser->getResultType());
		$oMawsParserResult ->save();
	}

	/**
	 * Возвращает сохранённые в БД записи этого треда
	 *
	 * @param timestamp $start - начало периода, за который вернуть записи
	 * @param timestamp $end - конец периода, за который вернуть записи
	 *
	 */
	public function getParserResults($start = false, $end = false)
	{

		$c = new Criteria();
		$c->add(MawsParserResultPeer::THREAD_ID,$this->getId());
		if ($start !== false)
		{
			$c->add(MawsParserResultPeer::CREATED_AT,$start,Criteria::LESS_THAN);
		}
		if ($end !== false)
		{
			$c->add(MawsParserResultPeer::CREATED_AT,$end,Criteria::GREATER_THAN);
		}
		$c->addDescendingOrderByColumn(MawsParserResultPeer::CREATED_AT);
		$arMawsParserResults = MawsParserResultPeer::doSelect($c);
		return $arMawsParserResults;
	}

	/**
	 *
	 * Возвращает список тредов, у который последнее обновление было слишком давно (больше, чем период обновления треда)
	 *
	 * @return array - arrqy of IDs of outdated threads
	 */
	static function getOutdatedThreads()
	{
		$debugPDO = Propel::getConnection();
		$query = 'SELECT ID FROM #1# WHERE now() - #2# > #3# ';
		$query = str_replace('#1#',MawsThreadPeer::TABLE_NAME,$query);
		$query = str_replace('#2#',MawsThreadPeer::CHECKED_AT,$query);
		$query = str_replace('#3#',MawsThreadPeer::UPDATE_PERIOD,$query);

		$statement = $debugPDO->prepare($query);
		$statement->execute(array());
		$thread_ids = $statement->fetchAll();
		
		return $thread_ids;
	}


} // MawsThread
