<?php


/**
 * Skeleton subclass for representing a row from the 'maws_page_thread' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Wed Mar 24 21:33:39 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MawsPageThread extends BaseMawsPageThread {

	/**
	 * Initializes internal state of MawsPageThread object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}


	/**
	 * Declares an association between this object and a MawsThread object.
	 *
	 * @param      MawsThread $v
	 * @return     MawsPageThread The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMawsThreadId($ThreadId)
	{
		if ($ThreadId === null) {
			$this->setThreadId(NULL);
		} else {
			$this->setThreadId($ThreadId);
		}
/*
		$this->aMawsThread = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the MawsThread object, it will not be re-added.
		if ($v !== null) {
			$v->addMawsPageThread($this);
		}
*/
		return $this;
	}

} // MawsPageThread
