<?php


/**
 * Skeleton subclass for representing a row from the 'maws_filter_result' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Sat Mar 20 00:50:39 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MawsFilterResult extends BaseMawsFilterResult {

	/**
	 * Initializes internal state of MawsFilterResult object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // MawsFilterResult
