<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sf_test' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Thu Mar 11 22:09:14 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SfTestPeer extends BaseSfTestPeer {

} // SfTestPeer
