# config/schema.yml
propel:

  maws_parser:
    id:           ~
    name:             { type: varchar(255), default: '' }
    description:      { type: varchar(255), default: '' }
    access:           { type: integer, required: true, default: 0 }
    resource_url:     { type: varchar(255) }
    resource_type:    { type: integer, required: true, default: 0 }
    resource_params:  { type: longvarchar, default: '' }
    resource_method:  { type: integer, required: true, default: 0 }
    resource_login:   { type: varchar(255) }
    resource_pass:    { type: varchar(255) }
    filter_type:      { type: integer, required: true, default: 0 }
    filter_params:    { type: longvarchar, default: '' }
    action_type:      { type: integer, required: true, default: 0 }
    action_params:    { type: longvarchar, default: '' }
    result_type:      { type: integer, required: true, default: 0 }
    owner_id:         { type: integer,  foreignTable: sf_guard_user, foreignReference: id, required: true }
    created_at:   ~
    updated_at:   ~


  maws_thread:
    id:           ~
    name:             { type: varchar(255), default: '' }
    description:      { type: varchar(255), default: '' }
    access:           { type: integer, required: true, default: 0 }
    parser_id:        { type: integer, required: true, default: 0 }
    update_start:     { type: timestamp, required: true }
    update_period:    { type: integer, required: true, default: 0 }
    result_type:      { type: integer, required: true, default: 0 }
    owner_id:         { type: integer,  foreignTable: sf_guard_user, foreignReference: id, required: true }
    checked_at:       { type: timestamp }
    created_at:   ~
    updated_at:   ~


  maws_parser_result:
    id:           ~
    name:             { type: varchar(255), default: '' }
    parser_id:        { type: integer,  foreignTable: maws_parser, foreignReference: id, required: true }
    thread_id:        { type: integer,  foreignTable: maws_thread, foreignReference: id, required: true }
    result_type:      { type: integer, required: true, default: 0 }
    result:           { type: longvarchar, default: '' }
    is_diff:          { type: integer, default: 0  }
    created_at:   ~

  maws_page:
    id:           ~
    name:             { type: varchar(255), default: '' }
    description:      { type: varchar(255), default: '' }
    access:           { type: integer, required: true, default: 0 }
    result_type:      { type: integer, required: true, default: 0 }
    show_period:      { type: integer, default: 0  }
    owner_id:         { type: integer,  foreignTable: sf_guard_user, foreignReference: id, required: true }
    created_at:   ~
    updated_at:   ~


  maws_page_thread:
    id:           ~
    page_id:          { type: integer,  foreignTable: maws_page, foreignReference: id, required: true }
    thread_id:        { type: integer,  foreignTable: maws_thread, foreignReference: id, required: true }
    sort_order:       { type: integer, default: 0  }
    color:            { type: integer, default: 0  }
    created_at:   ~
    updated_at:   ~

  sf_guard_user_profile:
    _attributes: { phpName: sfGuardUserProfile }
    id:          ~
    user_id:          { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    email:            { type: varchar(255), default: '' }
