<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/03/12 23:36:52

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=tangentau',
  'username' => 'root',
  'password' => 'mysqlrootpass',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
