<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/02 22:47:09
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => true,
  'app_sf_guard_plugin_success_signin_url' => '/main/index',
  'app_anonymous_login' => 'anonymous',
));
